// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFijqjuS7EdYZZ6Q18h6FksFO-ionTXhA',
    appId: '1:73699027275:web:b613a0b08c99acccfee0ce',
    messagingSenderId: '73699027275',
    projectId: 'flutter-firebase-storage-e62f3',
    authDomain: 'flutter-firebase-storage-e62f3.firebaseapp.com',
    storageBucket: 'flutter-firebase-storage-e62f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApW9vSyc5CK_i7MivRYG8abL6ybqK0wnk',
    appId: '1:73699027275:android:63f60da58e290605fee0ce',
    messagingSenderId: '73699027275',
    projectId: 'flutter-firebase-storage-e62f3',
    storageBucket: 'flutter-firebase-storage-e62f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs9JtpfGYJD-5Lmn_JpJilPR3-ooK8i_w',
    appId: '1:73699027275:ios:091a869dc965a0c6fee0ce',
    messagingSenderId: '73699027275',
    projectId: 'flutter-firebase-storage-e62f3',
    storageBucket: 'flutter-firebase-storage-e62f3.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseStorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs9JtpfGYJD-5Lmn_JpJilPR3-ooK8i_w',
    appId: '1:73699027275:ios:091a869dc965a0c6fee0ce',
    messagingSenderId: '73699027275',
    projectId: 'flutter-firebase-storage-e62f3',
    storageBucket: 'flutter-firebase-storage-e62f3.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseStorage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFijqjuS7EdYZZ6Q18h6FksFO-ionTXhA',
    appId: '1:73699027275:web:54f0e76e3ddd3dfdfee0ce',
    messagingSenderId: '73699027275',
    projectId: 'flutter-firebase-storage-e62f3',
    authDomain: 'flutter-firebase-storage-e62f3.firebaseapp.com',
    storageBucket: 'flutter-firebase-storage-e62f3.appspot.com',
  );
}
